server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:templates/thymeleaf/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 92e60583653691536dee
            client-secret: 8ed81b7b451039f19d521bde31fe4720c301144c

myBlog:
  password: githubpassword

logging:
  level:
    root: debug
