server:
  port: 8080

spring:
  config:
    import: github-keys.properties
  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:templates/thymeleaf/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: sa

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${client-id}
            client-secret: ${client-secret}

myBlog:
  password: ${githubpassword}

#logging:
#  level:
#    root: debug
