server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework: DEBUG